### PR TITLE
Ft user registration #162562518

### PR DESCRIPTION
**Pull request by Siffersari**
### What does this PR do?
This pull request creates a signup page where a user can create an account

### Description of tasks to be completed.

The following are the tasks to be completed:

    1.  Create HTML file for the signup page
    2.  Create CSS file for the signup page

### How should you manually test this?

    1. Clone this repository
        $ git clone https://github.com/Siffersari/StackOverflow-lite.git

    2. Switch to the StackOverflow-lite directory
        $ cd StackOverflow-lite

    3. Switch to the current branch
          $ ft-user-registration-162569680

    4.  Open index.html via any browser

### CODE REVIEW

**Comment by munniomer** [comment]
kindly add a screenshot of your UI so that we can review. And also add the relevant story ID

**Comment by munniomer** [comment]
And how you named your PR, is not the naming of Andela best practices

**Comment by Siffersari** [comment]
okay. I will take a look into that. Thank you so much @munniomer

**Comment by Siffersari** [comment]
@munniomer, I have made necessary changes. I believe the PR naming standard is that of Andela best practice?

**Comment by tirgei** [comment]
Nice work

**Comment by Siffersari** [comment]
@tirgei Thank you for your feedback.

**Comment by Bakley** [comment]
I see you doing great. Your work looks well thought of.

**Comment by Siffersari** [comment]
@Bakley  @Ogutu-Brian Thank you so much for your feedback. You guys literally keep me going.

**Pull request merged**
